spring.application.name=devsuPracticeBackend
spring.config.import=optional:file:../devsuPracticeDocker/.env[.properties]

# Datasource
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:devsu_bank}
spring.datasource.username=${POSTGRES_USER:devsu}
spring.datasource.password=${POSTGRES_PASSWORD:devsu123}

# JPA
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:validate}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

server.port=${SERVER_PORT:8080}
server.servlet.context-path=/api
