BEGIN;

-- Schema

CREATE TABLE customer (
    customer_id     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name            VARCHAR(100)  NOT NULL,
    gender          VARCHAR(20)   NOT NULL,
    age             INTEGER       NOT NULL,
    identification  VARCHAR(20)   NOT NULL,
    address         VARCHAR(200)  NOT NULL,
    phone           VARCHAR(20)   NOT NULL,
    password        VARCHAR(100)  NOT NULL,
    status          BOOLEAN       NOT NULL,
    CONSTRAINT pk_customer                PRIMARY KEY (customer_id),
    CONSTRAINT uk_customer_identification UNIQUE (identification),
    CONSTRAINT ck_customer_gender         CHECK (gender IN ('MALE', 'FEMALE', 'OTHER')),
    CONSTRAINT ck_customer_age            CHECK (age >= 0)
);

CREATE TABLE account (
    account_id      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    account_number  VARCHAR(20)    NOT NULL,
    account_type    VARCHAR(20)    NOT NULL,
    initial_balance NUMERIC(19,2)  NOT NULL,
    status          BOOLEAN        NOT NULL,
    customer_id     BIGINT         NOT NULL,
    CONSTRAINT pk_account                 PRIMARY KEY (account_id),
    CONSTRAINT uk_account_number          UNIQUE (account_number),
    CONSTRAINT ck_account_type            CHECK (account_type IN ('SAVINGS', 'CHECKING')),
    CONSTRAINT ck_account_initial_balance CHECK (initial_balance >= 0),
    CONSTRAINT fk_account_customer        FOREIGN KEY (customer_id) REFERENCES customer (customer_id)
);

CREATE TABLE transaction (
    transaction_id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    date             TIMESTAMP(6)   NOT NULL,
    transaction_type VARCHAR(20)    NOT NULL,
    amount           NUMERIC(19,2)  NOT NULL,
    balance          NUMERIC(19,2)  NOT NULL,
    account_id       BIGINT         NOT NULL,
    CONSTRAINT pk_transaction             PRIMARY KEY (transaction_id),
    CONSTRAINT ck_transaction_type        CHECK (transaction_type IN ('DEPOSIT', 'WITHDRAWAL')),
    CONSTRAINT ck_transaction_balance     CHECK (balance >= 0),
    CONSTRAINT fk_transaction_account     FOREIGN KEY (account_id) REFERENCES account (account_id)
);

-- Seed data

INSERT INTO customer (name, gender, age, identification, address, phone, password, status) VALUES
    ('Jose Lema',          'MALE',   35, '1710000001', 'Otavalo sn y principal', '098254785', '1234', TRUE),
    ('Marianela Montalvo', 'FEMALE', 29, '1710000002', 'Amazonas y NNUU',        '097548965', '5678', TRUE),
    ('Juan Osorio',        'MALE',   42, '1710000003', '13 junio y Equinoccial', '098874587', '1245', TRUE);

INSERT INTO account (account_number, account_type, initial_balance, status, customer_id) VALUES
    ('478758', 'SAVINGS',  2000.00, TRUE, (SELECT customer_id FROM customer WHERE identification = '1710000001')),
    ('225487', 'CHECKING',  100.00, TRUE, (SELECT customer_id FROM customer WHERE identification = '1710000002')),
    ('495878', 'SAVINGS',     0.00, TRUE, (SELECT customer_id FROM customer WHERE identification = '1710000003')),
    ('496825', 'SAVINGS',   540.00, TRUE, (SELECT customer_id FROM customer WHERE identification = '1710000002')),
    ('585545', 'CHECKING', 1000.00, TRUE, (SELECT customer_id FROM customer WHERE identification = '1710000001'));

INSERT INTO transaction (date, transaction_type, amount, balance, account_id) VALUES
    ('2022-02-10 10:00:00', 'WITHDRAWAL', -575.00, 1425.00, (SELECT account_id FROM account WHERE account_number = '478758')),
    ('2022-02-10 11:00:00', 'DEPOSIT',     600.00,  700.00, (SELECT account_id FROM account WHERE account_number = '225487')),
    ('2022-02-10 12:00:00', 'DEPOSIT',     150.00,  150.00, (SELECT account_id FROM account WHERE account_number = '495878')),
    ('2022-02-08 09:00:00', 'WITHDRAWAL', -540.00,    0.00, (SELECT account_id FROM account WHERE account_number = '496825'));

COMMIT;
