BEGIN;

-- Esquema

CREATE TABLE cliente (
    cliente_id      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre          VARCHAR(100)  NOT NULL,
    genero          VARCHAR(10)   NOT NULL,
    edad            INTEGER       NOT NULL,
    identificacion  VARCHAR(20)   NOT NULL,
    direccion       VARCHAR(200)  NOT NULL,
    telefono        VARCHAR(20)   NOT NULL,
    contrasena      VARCHAR(100)  NOT NULL,
    estado          BOOLEAN       NOT NULL,
    CONSTRAINT pk_cliente                PRIMARY KEY (cliente_id),
    CONSTRAINT uk_cliente_identificacion UNIQUE (identificacion),
    CONSTRAINT ck_cliente_genero         CHECK (genero IN ('MASCULINO', 'FEMENINO', 'OTRO')),
    CONSTRAINT ck_cliente_edad           CHECK (edad >= 0)
);

CREATE TABLE cuenta (
    cuenta_id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    numero_cuenta   VARCHAR(20)    NOT NULL,
    tipo_cuenta     VARCHAR(10)    NOT NULL,
    saldo_inicial   NUMERIC(19,2)  NOT NULL,
    estado          BOOLEAN        NOT NULL,
    cliente_id      BIGINT         NOT NULL,
    CONSTRAINT pk_cuenta                 PRIMARY KEY (cuenta_id),
    CONSTRAINT uk_cuenta_numero_cuenta   UNIQUE (numero_cuenta),
    CONSTRAINT ck_cuenta_tipo_cuenta     CHECK (tipo_cuenta IN ('AHORRO', 'CORRIENTE')),
    CONSTRAINT ck_cuenta_saldo_inicial   CHECK (saldo_inicial >= 0),
    CONSTRAINT fk_cuenta_cliente         FOREIGN KEY (cliente_id) REFERENCES cliente (cliente_id)
);

CREATE TABLE movimiento (
    movimiento_id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    fecha           TIMESTAMP(6)   NOT NULL,
    tipo_movimiento VARCHAR(10)    NOT NULL,
    valor           NUMERIC(19,2)  NOT NULL,   -- negativo en retiros
    saldo           NUMERIC(19,2)  NOT NULL,   -- saldo de la cuenta luego del movimiento
    cuenta_id       BIGINT         NOT NULL,
    CONSTRAINT pk_movimiento             PRIMARY KEY (movimiento_id),
    CONSTRAINT ck_movimiento_tipo        CHECK (tipo_movimiento IN ('DEPOSITO', 'RETIRO')),
    CONSTRAINT ck_movimiento_saldo       CHECK (saldo >= 0),
    CONSTRAINT fk_movimiento_cuenta      FOREIGN KEY (cuenta_id) REFERENCES cuenta (cuenta_id)
);

-- Datos iniciales

INSERT INTO cliente (nombre, genero, edad, identificacion, direccion, telefono, contrasena, estado) VALUES
    ('Jose Lema',          'MASCULINO', 35, '1710000001', 'Otavalo sn y principal', '098254785', '1234', TRUE),
    ('Marianela Montalvo', 'FEMENINO',  29, '1710000002', 'Amazonas y NNUU',        '097548965', '5678', TRUE),
    ('Juan Osorio',        'MASCULINO', 42, '1710000003', '13 junio y Equinoccial', '098874587', '1245', TRUE);

INSERT INTO cuenta (numero_cuenta, tipo_cuenta, saldo_inicial, estado, cliente_id) VALUES
    ('478758', 'AHORRO',    2000.00, TRUE, (SELECT cliente_id FROM cliente WHERE identificacion = '1710000001')),
    ('225487', 'CORRIENTE',  100.00, TRUE, (SELECT cliente_id FROM cliente WHERE identificacion = '1710000002')),
    ('495878', 'AHORRO',       0.00, TRUE, (SELECT cliente_id FROM cliente WHERE identificacion = '1710000003')),
    ('496825', 'AHORRO',     540.00, TRUE, (SELECT cliente_id FROM cliente WHERE identificacion = '1710000002')),
    ('585545', 'CORRIENTE', 1000.00, TRUE, (SELECT cliente_id FROM cliente WHERE identificacion = '1710000001'));

INSERT INTO movimiento (fecha, tipo_movimiento, valor, saldo, cuenta_id) VALUES
    ('2022-02-10 10:00:00', 'RETIRO',   -575.00, 1425.00, (SELECT cuenta_id FROM cuenta WHERE numero_cuenta = '478758')),
    ('2022-02-10 11:00:00', 'DEPOSITO',  600.00,  700.00, (SELECT cuenta_id FROM cuenta WHERE numero_cuenta = '225487')),
    ('2022-02-10 12:00:00', 'DEPOSITO',  150.00,  150.00, (SELECT cuenta_id FROM cuenta WHERE numero_cuenta = '495878')),
    ('2022-02-08 09:00:00', 'RETIRO',   -540.00,    0.00, (SELECT cuenta_id FROM cuenta WHERE numero_cuenta = '496825'));

COMMIT;
